global:
  extraEnv:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP

mimir:
  structuredConfig:
    memberlist:
      cluster_label: "{{.Release.Name}}-{{.Release.Namespace}}"

alertmanager:
  persistentVolume:
    enabled: true
  replicas: 1
  statefulSet:
    enabled: true
  zoneAwareReplication:
    enabled: false
  extraArgs:
    memberlist.advertise-addr: $(POD_IP)

compactor:
  persistentVolume:
    size: 10Gi
  extraArgs:
    memberlist.advertise-addr: $(POD_IP)

distributor:
  replicas: 1
  extraArgs:
    memberlist.advertise-addr: $(POD_IP)

ingester:
  persistentVolume:
    size: 10Gi
  replicas: 2
  topologySpreadConstraints: {}
  zoneAwareReplication:
    enabled: false
  statefulSet:
    enabled: true
  extraArgs:
    memberlist.advertise-addr: $(POD_IP)

admin-cache:
  enabled: true
  replicas: 1
  allocatedMemory: 64

chunks-cache:
  enabled: true
  replicas: 1
  allocatedMemory: 2048

index-cache:
  enabled: true
  replicas: 1
  allocatedMemory: 512

metadata-cache:
  enabled: true
  replicas: 1
  allocatedMemory: 128

results-cache:
  enabled: true
  replicas: 1
  allocatedMemory: 128

overrides_exporter:
  replicas: 1

querier:
  replicas: 1
  extraArgs:
    memberlist.advertise-addr: $(POD_IP)

query_frontend:
  replicas: 1
  extraArgs:
    memberlist.advertise-addr: $(POD_IP)

query_scheduler:
  enabled: true
  replicas: 1

ruler:
  replicas: 1
  remoteEvaluationDedicatedQueryPath: false
  extraArgs:
    memberlist.advertise-addr: $(POD_IP)

store_gateway:
  persistentVolume:
    size: 10Gi
  replicas: 1
  topologySpreadConstraints: {}
  zoneAwareReplication:
    enabled: false
  extraArgs:
    memberlist.advertise-addr: $(POD_IP)

nginx:
  enabled: false

gateway:
  enabled: true
  enabledNonEnterprise: true
  replicas: 1
  nginx:
    config:
      clientMaxBodySize: 10G

minio:
  enabled: true
  serviceAccount:
    create: true
    name: mimir-minio-sa