alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 1

grafana:
  enabled: true
  defaultDashboardsTimezone: America/Toronto
  defaultDashboardsEditable: true
  defaultDashboardsInterval: 1m
  adminUser: admin
  adminPassword: prom-operator
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - ""
    path: /
    tls:
      - secretName: tls-domain
  persistence:
    enabled: true
    type: sts
    storageClassName: rook-ceph-block
    accessModes:
      - ReadWriteOnce
    size: 10Gi
    finalizers:
      - kubernetes.io/pvc-protection

prometheusOperator:
  enabled: true
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 10
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 10
    successThreshold: 1

prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
    maximumStartupDurationSeconds: 120
    remoteWrite:
      - url: http://mimir-gateway/api/v1/push
    serviceMonitorSelector:
      matchLabels:
        release: prometheus
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: rook-ceph-block
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
