crds:
  keep: false

controller:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus
  logging:
    level: debug

server:
  logging:
    level: debug
  authModes:
    - sso
  sso:
    enabled: true
    issuer: ""
    clientId:
      name: argo-server-sso
      key: client-id
    clientSecret:
      name: argo-server-sso
      key: client-secret
    redirectUrl: ""
    scopes:
      - openid
      - email
      - groups
      - profile
    insecureSkipVerify: true
    sessionExpiry: 240h
    rbac:
      enabled: true
      policy: |
        g, marchehub:DevOps, role:admin
        p, role:admin, *, *, allow
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - ""
