global:
  defaultStorageClass: rook-ceph-block

auth:
  username: rabbitmq-admin
  existingPasswordSecret: rabbitmq-secrets
  existingSecretPasswordKey: rabbitmq-password

logs: false

clustering:
  enabled: true
  forceBoot: true
  partitionHandling: autoheal

replicaCount: 3

persistence:
  enabled: true
  storageClass: rook-ceph-block
  size: 5Gi

service:
  type: ClusterIP

volumePermissions:
  enabled: true
  resources:
    requests:
      cpu: 1
      memory: 128Mi
    limits:
      cpu: 2
      memory: 256Mi

resources:
  requests:
    cpu: 1
    memory: 256Mi
  limits:
    cpu: 2
    memory: 512Mi
