global:
  defaultStorageClass: rook-ceph-block

auth:
  username: rabbitmq-admin
  existingPasswordSecret: rabbitmq-secrets
  existingSecretPasswordKey: rabbitmq-password

logs: false

clustering:
  enabled: true
  forceBoot: true
  partitionHandling: autoheal

replicaCount: 1

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 400m
    memory: 256Mi

persistence:
  enabled: true
  storageClass: rook-ceph-block
  size: 5Gi

volumePermissions:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: ""
  path: /
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 120s
    default:
      enabled: true
    perObject:
      enabled: true
    detailed:
      enabled: true
    labels:
      release: prometheus
