apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
      - name: mysecret
        mountPath: /tmp/secret1
        readOnly: true
  volumes:
    - name: mysecret
      secret:
        secretName: secret1
        items:
          - key: username
            path: a/u
          - key: password
            path: b/p
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp2
  labels:
    name: myapp2
spec:
  containers:
  - name: myapp2
    image: nginx
    ports:
      - containerPort: 80
    env:
      - name: username
        valueFrom:
          secretKeyRef:
            name: secret1
            key: username
      - name: password
        valueFrom:
          secretKeyRef:
            name: secret1
            key: password
