pyroscope:
  extraEnvVars:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
  extraArgs:
    memberlist.advertise-addr: $(POD_IP)
  replicaCount: 1
  persistence:
    enabled: true
    size: 10Gi
  startupProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 30
    failureThreshold: 10
  readinessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 30
    failureThreshold: 10
  livenessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 10
    failureThreshold: 10
  # structuredConfig:
  #   storage:
  #     backend: s3
  #     s3:
  #       endpoint: ""
  #       bucket_name: pyroscope-data
  #       access_key_id:
  #       secret_access_key:
  #       insecure: false

alloy:
  enabled: false

agent:
  enabled: false

minio:
  enabled: true
  serviceAccount:
    create: true
    name: pyroscope-minio-sa

ingress:
  enabled: false

serviceMonitor:
  enabled: false
