externalURL: ""

expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: tls-domain
  ingress:
    hosts:
      core: ""
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"

existingSecretAdminPassword: harbor-secrets
existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD

database:
  type: external
  external:
    host: "postgresql"
    port: "5432"
    username: "harbor"
    coreDatabase: "harbor"
    existingSecret: "postgres-secrets"

redis:
  type: external
  external:
    addr: "redis-master:6379"
    existingSecret: "redis-secrets"

exporter:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi

persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      storageClass: "rook-ceph-block"
      size: 10Gi
    jobservice:
      jobLog:
        storageClass: "rook-ceph-block"
    trivy:
      storageClass: "rook-ceph-block"

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus