global:
  time_zone: UTC
  edition: ce
  ingress:
    enabled: true
    apiVersion: "networking.k8s.io/v1"
    configureCertmanager: false
    useNewIngressForCerts: false
    class: "nginx"
    provider: "nginx"
    tls:
      enabled: true
      secretName: tls-domain
    path: "/"
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    domain: ""
    externalIP: 10.20.1.1
    https: false
    gitlab:
      https: true
      name: ""
    minio:
      https: true
      name: ""
    ssh: ""
  rails:
    bootsnap:
      enabled: false
  psql:
    host: postgresql-primary
    port: 5432
    username: gitlab
    database: gitlabhq_production
    password:
      useSecret: true
      secret: postgres-secrets
      key: gitlab-password
    connectTimeout: 120
    preparedStatements: true
  redis:
    host: redis-master
    port: 6379
    database: 6
    auth:
      enabled: true
      secret: redis-secrets
      key: redis-password
  kas:
    enabled: false
  registry:
    enabled: false
  webservice:
    workerTimeout: 240
  shell:
    port: 222
    tcp:
      proxyProtocol: true

gitlab:
  webservice:
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
    workhorse:
      resources:
        requests:
          cpu: 500m
          memory: 500Mi
        limits:
          cpu: 1
          memory: 1Gi
  sidekiq:
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
      limits:
        cpu: 1
        memory: 1Gi
    readinessProbe:
      initialDelaySeconds: 60
      periodSeconds: 20
      timeoutSeconds: 20
      successThreshold: 1
      failureThreshold: 10
    livenessProbe:
      initialDelaySeconds: 90
      periodSeconds: 15
      timeoutSeconds: 15
      successThreshold: 1
      failureThreshold: 10
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 2
    service:
      type: NodePort
      nodePort: 30022

installCertmanager: false

prometheus:
  install: false

postgresql:
  install: false

registry:
  enabled: false

gitlab-runner:
  install: false

redis:
  install: false

nginx-ingress:
  enabled: false

nginx-ingress-geo:
  enabled: false

gitlab-zoekt:
  install: false

traefik:
  install: false

haproxy:
  install: false
