global:
  storageClass: rook-ceph-block

auth:
  enabled: true
  existingSecret: redis-secrets

commonConfiguration: |-
  maxmemory-policy volatile-lru
  appendonly yes
  save 900 1
  save 300 10
  save 60 10000

architecture: standalone

master:
  count: 1
  persistence:
    enabled: true
    size: 5Gi
  disableCommands:
    - FLUSHDB
  terminationGracePeriodSeconds: 60
  startupProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 20
    timeoutSeconds: 20
    successThreshold: 1
    failureThreshold: 30
  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 20
    timeoutSeconds: 20
    successThreshold: 1
    failureThreshold: 10
  livenessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 15
    timeoutSeconds: 15
    successThreshold: 1
    failureThreshold: 10

# architecture: replication
# replica:
#   replicaCount: 3
#   disableCommands:
#     - FLUSHDB
#   persistence:
#     enabled: true
#     storageClass: rook-ceph-block
#     size: 5Gi
#   terminationGracePeriodSeconds: 60
#   startupProbe:
#     enabled: true
#     initialDelaySeconds: 60
#     periodSeconds: 20
#     timeoutSeconds: 20
#     successThreshold: 1
#     failureThreshold: 30
#   readinessProbe:
#     enabled: true
#     initialDelaySeconds: 60
#     periodSeconds: 20
#     timeoutSeconds: 20
#     successThreshold: 1
#     failureThreshold: 10
#   livenessProbe:
#     enabled: true
#     initialDelaySeconds: 90
#     periodSeconds: 15
#     timeoutSeconds: 15
#     successThreshold: 1
#     failureThreshold: 10

# sentinel:
#   enabled: true
#   masterSet: mymaster
#   quorum: 2
#   replicas: 3
#   terminationGracePeriodSeconds: 60
#   persistence:
#     enabled: true
#     storageClass: rook-ceph-block
#     size: 100Mi
#   startupProbe:
#     enabled: true
#     initialDelaySeconds: 60
#     periodSeconds: 15
#     timeoutSeconds: 15
#     failureThreshold: 20
#   readinessProbe:
#     enabled: true
#     initialDelaySeconds: 60
#     periodSeconds: 10
#     timeoutSeconds: 10
#     failureThreshold: 10
#   livenessProbe:
#     enabled: true
#     initialDelaySeconds: 90
#     periodSeconds: 15
#     timeoutSeconds: 10
#     failureThreshold: 10

volumePermissions:
  enabled: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: prometheus
  startupProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 20
    timeoutSeconds: 20
    successThreshold: 1
    failureThreshold: 10
  livenessProbe:
    enabled: true
    initialDelaySeconds: 90
    periodSeconds: 10
    timeoutSeconds: 10
    successThreshold: 1
    failureThreshold: 5
  readinessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 5
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
