architecture: replication

auth:
  enabled: true
  existingSecret: redis-secrets

master:
  count: 1
  persistence:
    enabled: true
    storageClass: rook-ceph-block
    size: 5Gi
  resources:
    requests:
      cpu: 1
      memory: 256Mi
    limits:
      cpu: 2
      memory: 256Mi

replica:
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: rook-ceph-block
    size: 5Gi
  resources:
    requests:
      cpu: 1
      memory: 256Mi
    limits:
      cpu: 1
      memory: 256Mi

sentinel:
  enabled: true
  masterSet: mymaster
  quorum: 3
  replicas: 3
  resources:
    requests:
      cpu: 1
      memory: 256Mi
    limits:
      cpu: 1
      memory: 256Mi