replicas: 1

tempo:
  reportingEnabled: false
  multitenancyEnabled: false

serviceMonitor:
  enabled: true
  interval: "120s"
  additionalLabels:
    release: prometheus
  scrapeTimeout: 10s

persistence:
  enabled: true
  size: 10Gi